module.exports = [
  'Aachen',
  'Aalborg',
  'Aberdeen',
  'Abilene',
  'Aix-en-Provence',
  'Akron',
  'Albany',
  'Alberta',
  'Albi',
  'Albuquerque',
  'Alexandria',
  'Allentown',
  'Altenburg',
  'Altkirch',
  'Amarillo',
  'Amiens',
  'Amman',
  'Amsterdam',
  'Anaheim',
  'Anchorage',
  'Ann Arbor',
  'Antioch',
  'Antwerp',
  'Apple Valley',
  'Appleton',
  'Arles',
  'Arlington',
  'Arvada',
  'Asheville',
  'Athens',
  'Atlanta',
  'Atlantic City',
  'Atwerp',
  'Auckland',
  'Augusta',
  'Aurora',
  'Austin',
  'Avignon',
  'Baden-Baden',
  'Bakersfield',
  'Baltimore',
  'Barcelona',
  'Barnstable',
  'Basel',
  'Baton Rouge',
  'Beaumont',
  'Beijing',
  'Beirut',
  'Bel Air',
  'Belfort',
  'Bellevue',
  'Bergamo',
  'Bergen',
  'Berkeley',
  'Berlin',
  'Bern',
  'Besançon',
  'Bethlehem',
  'Biel',
  'Bignan',
  'Bilbao',
  'Billings',
  'Birmingham',
  'Bloomington',
  'Boadilla',
  'Boise',
  'Boise City',
  'Boissy-le-Chatel',
  'Bologna',
  'Bolzano',
  'Bonita Springs',
  'Bonn',
  'Bordeaux',
  'Boston',
  'Boulder',
  'Bozen',
  'Bradenton',
  'Bregenz',
  'Bremen',
  'Bremerhaven',
  'Bremerton',
  'Brest',
  'Bridgeport',
  'Brighton',
  'Brisbane',
  'Brownsville',
  'Brussels',
  'Bryan',
  'Buenos Aires',
  'Buffalo',
  'Burbank',
  'Burgdorf',
  'Burlington',
  'Cadillac Gironde',
  'Cajarc',
  'Calais',
  'Cambridge',
  'Cannes',
  'Canton',
  'Cape Coral',
  'Caracas',
  'Caraglio',
  'Carquefou',
  'Carrollton',
  'Cary',
  'Cascais',
  'Catania',
  'Cathedral City',
  'Cedar Rapids',
  'Celle',
  'Cetinje',
  'Chalon-sur-Saone',
  'Chambery',
  'Champaign',
  'Chandler',
  'Charleroi',
  'Charleston',
  'Charlotte',
  'Charlottenlund',
  'Chattanooga',
  'Chemnitz',
  'Chesapeake',
  'Chicago',
  'Chieti',
  'Chula Vista',
  'Cincinnati',
  'Clarke County',
  'Clarksville',
  'Clearwater',
  'Cleveland',
  'Codriopo',
  'College Station',
  'Cologne',
  'Colorado Springs',
  'Columbia',
  'Columbus',
  'Concord',
  'Copenhagen',
  'Coral Springs',
  'Cork',
  'Corona',
  'Corpus Christi',
  'Costa Mesa',
  'Crete',
  'Cuenca',
  'Cuernavaca',
  'Cully',
  'Curitiba',
  'Cáceres',
  'Dakar',
  'Dallas',
  'Daly City',
  'Danbury',
  'Darmstadt',
  'Davenport',
  'Davidson County',
  'Dayton',
  'Daytona Beach',
  'Deltona',
  'Denton',
  'Denver',
  'Des Moines',
  'Dessao',
  'Dessau',
  'Detroit',
  'Deurle',
  'Dijon',
  'Dordogne',
  'Dortmund',
  'Downey',
  'Dresden',
  'Dublin',
  'Dudweier',
  'Duisburg',
  'Duluth',
  'Dunedin',
  'Dunkirk',
  'Durham',
  'Dusseldorf',
  'Düsseldorf',
  'Edinburgh',
  'Eindhoven',
  'El Monte',
  'El Paso',
  'Elizabeth',
  'Elk Grove',
  'Elkhart',
  'Erfurt',
  'Erie',
  'Erlangen',
  'Escondido',
  'Essen',
  'Esslingen',
  'Estavar',
  'Eugene',
  'Evansville',
  'Eveux',
  'Fairfield',
  'Fargo',
  'Fayetteville',
  'Fellbach',
  'Fitchburg',
  'Flint',
  'Florence',
  'Fontana',
  'Fort Collins',
  'Fort Lauderdale',
  'Fort Smith',
  'Fort Walton Beach',
  'Fort Wayne',
  'Fort Worth',
  'Frankfurt',
  'Frederick',
  'Fremont',
  'Fresno',
  'Fukui City',
  'Fukuoka',
  'Fullerton',
  'Gainesville',
  'Garden Grove',
  'Garland',
  'Gastonia',
  'Geneva',
  'Genoa',
  'Gent',
  'Ghent',
  'Gibellina',
  'Gijon',
  'Gijón',
  'Gilbert',
  'Girona',
  'Glendale',
  'Goppingen',
  'Goslar',
  'Gothenburg',
  'Granada',
  'Grand Prairie',
  'Grand Rapids',
  'Grayslake',
  'Graz',
  'Green Bay',
  'GreenBay',
  'Greensboro',
  'Greenville',
  'Grenoble',
  'Groningen',
  'Guadalajara',
  'Guangdong Province',
  'Guangzhou',
  'Guelph (ON)',
  'Guimaraes',
  'Gulfport-Biloxi',
  'Göteborg',
  'Haale',
  'Hagerstown',
  'Hamburg',
  'Hamilton',
  'Hampton',
  'Hannover',
  'Harlingen',
  'Harrisburg',
  'Hartford',
  'Hasselt',
  'Haute-Vienne',
  'Havana',
  'Havre de Grace',
  'Hayward',
  'Helsinki',
  'Hemet',
  'Henderson',
  'Herculaneum',
  'Herford',
  'Herning',
  'Herzliya',
  'Hesperia',
  'Hialeah',
  'Hickory',
  'High Point',
  'Hobart',
  'Hollywood',
  'Holte',
  'Hong Kong',
  'Honolulu',
  'Horn',
  'Hornu',
  'Houma',
  'Houston',
  'Howell',
  'Humlebaek',
  'Huntington',
  'Huntington Beach',
  'Huntsville',
  'Hydra',
  'Ibos',
  'Ile de Vassiviere',
  'Independence',
  'Indianapolis',
  'Inglewood',
  'Innsbruck',
  'Irvine',
  'Irving',
  'Istanbul',
  'Jackson',
  'Jacksonville',
  'Jefferson',
  'Jersey City',
  'Jerusalem',
  'Jevnaker',
  'Johnson City',
  'Joliet',
  'Jouy-en-Josas',
  'Kailua',
  'Kalamazoo',
  'Kanazawa',
  'Kaneohe',
  'Kansas City',
  'Karlsrue',
  'Karlsruhe',
  'Kassel',
  'Kennewick',
  'Kenosha',
  'Kiel',
  'Kiev',
  'Killeen',
  'Kissimmee',
  'Kitakyushu',
  'Klagenfurt',
  'Klosterneuburg',
  'Knoxville',
  'Kobe',
  'Kochi',
  'Kortrijk',
  'Krabbesholm',
  'Krefeld',
  'Kunsthaus Graz',
  'Kyiv',
  'Künzelsau',
  'La Louvière',
  'Lacey',
  'Lafayette',
  'Lake Charles',
  'Lakeland',
  'Lakewood',
  'Lancaster',
  'Lansing',
  'Laredo',
  'Las Cruces',
  'Las Vegas',
  'Lasipalatsi',
  'Layton',
  'Le Havre',
  'Leidsche Rijn',
  'Leipzig',
  'Leominster',
  'Lewisville',
  'Lexington',
  'León',
  'Lincoln',
  'Linz',
  'Lisbon',
  'Lismore',
  'Little Rock',
  'Liège',
  'Ljubljana',
  'Locarno',
  'location',
  'Locminé Bignan',
  'Lodz',
  'Lolland',
  'Long Beach',
  'Lorain',
  'Los Angeles',
  'Louisville',
  'Lowell',
  'Lubbock',
  'Lubljana',
  'Lucerne',
  'Ludwigshafen',
  'Lugano',
  'Lund',
  'Luzern',
  'Lyon',
  'Macon',
  'Madison',
  'Madrid',
  'Malmö',
  'Malmø',
  'Manchester',
  'Mannheim',
  'Marina',
  'Marl',
  'Marrakech',
  'Marseille',
  'Marseilles',
  'Marysville',
  'McAllen',
  'McHenry',
  'Mechelen',
  'Medford',
  'Melbourne',
  'Memphis',
  'Merced',
  'Mesa',
  'Mesquite',
  'Metz',
  'Mexico',
  'Mexico City',
  'Mexico D.F.',
  'Meymac',
  'Miami',
  'Milan',
  'Milano',
  'Milwaukee',
  'Minato',
  'Minneapolis',
  'Miramar',
  'Mission Viejo',
  'Mito-shi Ibaraki',
  'Mobile',
  'Modesto',
  'Monfalcone',
  'Monroe',
  'Mons',
  'Monterey',
  'Monterrey',
  'Montgomery',
  'Montpellier',
  'Montreal',
  'Moreno Valley',
  'Mouans-Sartoux',
  'Muenster',
  'Munich',
  'Munster',
  'Murcia',
  'Murfreesboro',
  'Murrieta',
  'Muskegon',
  'Myrtle Beach',
  'Mönchengladbach',
  'Münchenstein',
  'Münster',
  'Nagasaki',
  'Nagoya',
  'Nanjing',
  'Nantes',
  'Naoshima',
  'Naperville',
  'Naples',
  'Napoli',
  'Nashua',
  'Nashville',
  'New Bedford',
  'New Haven',
  'New London',
  'New Orleans',
  'New York',
  'New York City',
  'Newark',
  'Newburgh',
  'Newport News',
  'Nice',
  'Norfolk',
  'Normal',
  'Norman',
  'North Charleston',
  'North Las Vegas',
  'North Port',
  'Norwalk',
  'Norwich',
  'Nottingham',
  'Nova Scotia',
  'Nuoro',
  'Nuremberg',
  'Nuremburg',
  'Nîmes',
  'Nürnberg',
  'Oakland',
  'Oberhausen',
  'Ocala',
  'Oceanside',
  'Odessa',
  'Ogden',
  'Oklahoma City',
  'Olathe',
  'Olympia',
  'Omaha',
  'Ontario',
  'Oostende',
  'Oporto',
  'Orange',
  'Orem',
  'Orlando',
  'Oslo',
  'Ostend',
  'Oudenburg',
  'Overland Park',
  'Oxnard',
  'Palm Bay',
  'Palm Springs',
  'Palmdale',
  'Panama City',
  'Paris',
  'Pasadena',
  'Passariano',
  'Paterson',
  'Pejë',
  'Pembroke Pines',
  'Pensacola',
  'Peoria',
  'Philadelphia',
  'Phoenix',
  'Piacenza',
  'Pittsburgh',
  'Plano',
  'Pomona',
  'Pompano Beach',
  'Pontault Combault',
  'Port Arthur',
  'Port Orange',
  'Port Saint Lucie',
  'Port St. Lucie',
  'Porte Alegro',
  'Portland',
  'Porto',
  'Porto Alegre',
  'Portsmouth',
  'Poughkeepsie',
  'Pougues-les-Eaux',
  'Pougueslers-Eaux',
  'Poznan',
  'Prague',
  'Prato',
  'Pretoria',
  'Providence',
  'Provo',
  'Puebla',
  'Pueblo',
  'Punta Gorda',
  'Quedlinburg',
  'Racine',
  'Raleigh',
  'Rancho Cucamonga',
  'Reading',
  'Recklinghausen',
  'Redding',
  'Regensburg',
  'Reggio nell\'Emilia',
  'Reims',
  'Rennes',
  'Reno',
  'Reykjavik',
  'Richland',
  'Richmond',
  'Richmond County',
  'Rijeka',
  'Rio de Janeiro',
  'Rio do Janeiro',
  'Riverside',
  'Roanoke',
  'Rochechouart',
  'Rochester',
  'Rockford',
  'Rome',
  'Roseville',
  'Rotterdam',
  'Rottweil',
  'Rouen',
  'Round Lake Beach',
  'Rovereto',
  'Sacramento',
  'Saginaw',
  'Saint Louis',
  'Saint Paul',
  'Saint Petersburg',
  'Saint-Nazaire',
  'Saint-Ouen',
  'SaintPriest',
  'Saitama',
  'Salamanca',
  'Salem',
  'Salinas',
  'Salt Lake City',
  'Salzburg',
  'San Antonio',
  'San Bernardino',
  'San Buenaventura',
  'San Diego',
  'San Francisco',
  'San Gimignano',
  'San Jose',
  'San Juan',
  'Santa Ana',
  'Santa Barbara',
  'Santa Clara',
  'Santa Clarita',
  'Santa Cruz',
  'Santa Maria',
  'Santa Rosa',
  'Santiago',
  'Santiago de Compostela',
  'Sao Paolo',
  'Sao Paulo',
  'Sarasota',
  'Savannah',
  'Scottsdale',
  'Scranton',
  'Seaside',
  'Seattle',
  'Sebastian',
  'Seville',
  'Shanghai',
  'Shanghai and Shenzhen',
  'Shenzhen',
  'Shreveport',
  'Sienna',
  'Simi Valley',
  'Sindelfingen',
  'Singapore Art Museum',
  'Sioux City',
  'Sioux Falls',
  'Sittard',
  'Skarhamn',
  'Sotteville-lès-Rouen',
  'South Bend',
  'South Lyon',
  'Spartanburg',
  'Spokane',
  'Springdale',
  'Springfield',
  'St. Gallen',
  'St. Louis',
  'St. Paul',
  'St. Petersburg',
  'Stamford',
  'Sterling Heights',
  'Stockholm',
  'Stockton',
  'Strasbourg',
  'Stuttgart',
  'Sunnyvale',
  'Sydney',
  'Syracuse',
  'São Paulo',
  'Tacoma',
  'Taipei',
  'Tallahassee',
  'Tampa',
  'Tampere',
  'Tatebayashi',
  'Tbilisi',
  'Tel Aviv',
  'Temecula',
  'Tempe',
  'Terni',
  'The Hague',
  'Thessaloniki',
  'Thornton',
  'Thousand Oaks',
  'Thun',
  'Tijuana',
  'Tilburg',
  'Tirana',
  'Tokyo',
  'Toledo',
  'Topeka',
  'Torino',
  'Toronto',
  'Torrance',
  'Toulon',
  'Toulouse',
  'Tourcoing',
  'Tournus',
  'Toyama',
  'Trento',
  'Trenton',
  'Trier',
  'Trieste',
  'Tucson',
  'Tulette',
  'Tulsa',
  'Turin',
  'Turku',
  'Tuscaloosa',
  'Tyler',
  'Uppsala',
  'Utica',
  'Vaduz',
  'Valby',
  'Valence',
  'Valencia',
  'Vallejo',
  'Vancouver',
  'Venice',
  'Vero Beach',
  'Vestfossen',
  'Vevey',
  'Victorville',
  'Vienna',
  'Vigo',
  'Villach',
  'Villeurbanne',
  'Virginia Beach',
  'Visalia',
  'Visby',
  'Vitoria',
  'Volterra',
  'Waco',
  'Warren',
  'Warsaw',
  'Warwickshire',
  'Washington',
  'Waterbury',
  'Waterloo',
  'West Covina',
  'West Valley City',
  'Westminster',
  'Wichita',
  'Wiesbaden',
  'Wijnegem',
  'Wilmington',
  'Winston',
  'Winter Haven',
  'Winterthur',
  'Wolfsburg',
  'Worcester',
  'Wuppertal',
  'Yakima',
  'Yokohama',
  'Yonkers',
  'York',
  'Youngstown',
  'Zagreb',
  'Zhengzhou',
  'Zurich',
  'Zürich',
  'Óbidos',
]
